language: ruby

sudo: false

cache: bundler

before_install:
  - gem update --system

script:
  - "ruby -e \"RUBY_VERSION.match?(/^2\.5\.\d+/) ? system('bundle exec rubocop') : exit(0)\""
  - bundle exec rake spec

rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5

gemfile:
  - gemfiles/rails_3.0.gemfile
  - gemfiles/rails_3.1.gemfile
  - gemfiles/rails_3.2.gemfile
  - gemfiles/rails_4.0.gemfile
  - gemfiles/rails_4.1.gemfile
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile

matrix:
  exclude:
  # Rails 5+ requires Ruby 2.2+
  - rvm: 2.0
    gemfile: gemfiles/rails_5.0.gemfile
  - rvm: 2.0
    gemfile: gemfiles/rails_5.1.gemfile
  - rvm: 2.1
    gemfile: gemfiles/rails_5.0.gemfile
  - rvm: 2.1
    gemfile: gemfiles/rails_5.1.gemfile

  # Rails 4.0 and 4.1 requires an old version of `json` gem, which isn't compatible with Ruby 2.4+
  # https://github.com/flori/json/issues/308
  - rvm: 2.4
    gemfile: gemfiles/rails_4.0.gemfile
  - rvm: 2.4
    gemfile: gemfiles/rails_4.1.gemfile
  - rvm: 2.5
    gemfile: gemfiles/rails_4.0.gemfile
  - rvm: 2.5
    gemfile: gemfiles/rails_4.1.gemfile

  # Rails 3.0 doesn't work with Ruby 2.5
  # (`undefined method `yaml_as' for BigDecimal:Class`)
  - rvm: 2.5
    gemfile: gemfiles/rails_3.0.gemfile

addons:
  code_climate:
    repo_token: 60e4a18e2a4bc86a98f92847f16756876c13d1e772058a9b3296643b04a697d7
