name: CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      fail-fast: false

      matrix:
        ruby:
          - 3.0
          - 3.1
          - 3.2
          - 3.3
        gemfile:
          - gemfiles/rails_6.0.gemfile
          - gemfiles/rails_6.1.gemfile
          - gemfiles/rails_7.0.gemfile
          - gemfiles/rails_7.1.gemfile
          - gemfiles/rails_7.2.gemfile

    env:
      BUNDLE_GEMFILE: "${{ matrix.gemfile }}"

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Rubocop
      if: ${{ matrix.ruby == '3.3' }}
      run: "bundle exec rubocop"

    - name: Tests
      run: bundle exec rake spec
